from common import quiz, B1

quiz("b1-01", course=B1, n=1, lesson="lesson-01-present-simple-vs-continuous.html",
  name="Present Simple vs Present Continuous",
  structures="present simple (base verb + s) vs present continuous (am/is/are + -ing); stative verbs",
  tags=["present-simple", "present-continuous", "stative-verbs"], qs=[
  ("mcq", "Look — the manager ___ with the new employee right now.", ["is talking", "talks", "talk", "has talked"], 0),
  ("gap", "Water ___ (boil) at 100°C at sea level.", "boils", []),
  ("tf", "Stative verbs like 'understand' and 'believe' are rarely used in the continuous, so 'I am understanding' is wrong.", True),
  ("mcq", "Our team usually ___ on Monday mornings.", ["meets", "is meeting", "meet", "are meeting"], 0),
  ("spot", "She is knowing exactly what you mean.", ["She", "is knowing", "exactly", "what you mean"], 1),
  ("mcq", "She's currently ___ the London project — it ends in May.", ["managing", "manages", "manage", "managed"], 0),
  ("gap", "This month, the team ___ (work) on a very tight deadline.", "is working", ["'s working", "’s working"]),
  ("wb", "Unscramble the missing verb: I ___ that expectations can shape performance.", "BELIEVE"),
  ("mcq", "Which sentence describes a TEMPORARY situation?", ["I'm working with data on this project.", "I work with data.", "Data analysis is my job.", "I always work with data."], 0),
  ("tf", "Words like 'currently' and 'these days' always need the present continuous.", False),
  ("gap", "Teachers' expectations often ___ (shape) how their students perform.", "shape", []),
  ("spot", "I am wanting a coffee right now.", ["I", "am wanting", "a coffee", "right now"], 1),
])

quiz("b1-02", course=B1, n=2, lesson="lesson-02-past-simple-vs-continuous.html",
  name="Past Simple vs Past Continuous",
  structures="past simple (verb + -ed / irregular) vs past continuous (was/were + -ing); interrupted actions and background scenes",
  tags=["past-simple", "past-continuous"], qs=[
  ("mcq", "While I ___ dinner, the phone rang.", ["was cooking", "cooked", "am cooking", "have cooked"], 0),
  ("gap", "She ___ (finish) the report yesterday afternoon.", "finished", []),
  ("mcq", "When the phone rang, I ___ it straight away.", ["answered", "was answering", "answer", "have answered"], 0),
  ("tf", "In 'When the phone rang, I was taking a shower', the shower started before the phone rang.", True),
  ("gap", "At midnight, they ___ (discuss) the results.", "were discussing", []),
  ("spot", "I was knowing the answer, but I didn't say anything.", ["I", "was knowing", "the answer", "didn't say anything"], 1),
  ("mcq", "The researcher ___ his famous paper in 1955.", ["published", "was publishing", "publishes", "has published"], 0),
  ("wb", "Unscramble the missing word: They ___ playing tennis when it started to rain.", "WERE"),
  ("mcq", "Which sentence sets the background scene of a story?", ["The sun was shining and people were walking by.", "The sun came out.", "She opened the door.", "He left at 6 pm."], 0),
  ("tf", "'He was travelling to Berlin three times last year' is correct.", False),
  ("gap", "She ___ (review) the data when she noticed something strange.", "was reviewing", []),
  ("mcq", "I ___ TV when I heard a strange noise outside.", ["was watching", "watched", "am watching", "have watched"], 0),
])

quiz("b1-03", course=B1, n=3, lesson="lesson-03-present-perfect-vs-past-simple.html",
  name="Present Perfect vs Past Simple",
  structures="present perfect (have/has + past participle) vs past simple; for/since, ever/never, finished vs unfinished time",
  tags=["present-perfect", "past-simple"], qs=[
  ("mcq", "She ___ here since 2019.", ["has worked", "worked", "works", "is working"], 0),
  ("mcq", "They ___ the report yesterday.", ["finished", "have finished", "has finished", "finish"], 0),
  ("gap", "I ___ (never/visit) South America.", "have never visited", ["'ve never visited", "’ve never visited"]),
  ("tf", "'I lived in Warsaw for five years' suggests I don't live there any more.", True),
  ("spot", "Two psychologists have coined the term in 1978.", ["Two psychologists", "have coined", "the term", "in 1978"], 1),
  ("mcq", "Which time expression goes with the present perfect?", ["so far", "yesterday", "in 2015", "last month"], 0),
  ("gap", "Researchers ___ (study) this phenomenon for decades.", "have studied", ["have been studying"]),
  ("wb", "Unscramble the missing word: Have you ___ felt like a fraud at work?", "EVER"),
  ("mcq", "The company ___ three new offices this year.", ["has opened", "opens", "open", "have opened"], 0),
  ("tf", "'I have seen him yesterday' is correct.", False),
  ("gap", "He ___ (join) the company in 2015.", "joined", []),
  ("mcq", "Have you ever ___ to Japan?", ["been", "went", "go", "being"], 0),
])

quiz("b1-04", course=B1, n=4, lesson="lesson-04-present-perfect-simple-vs-continuous.html",
  name="Present Perfect Simple vs Present Perfect Continuous",
  structures="present perfect simple (have/has + past participle) for results vs present perfect continuous (have/has been + -ing) for activity",
  tags=["present-perfect", "present-perfect-continuous"], qs=[
  ("mcq", "She ___ on this project for three hours.", ["has been working", "is working", "works", "was working"], 0),
  ("mcq", "He ___ five emails this morning.", ["has written", "has been writing", "is writing", "writes"], 0),
  ("gap", "I ___ (read) all afternoon — my eyes are tired.", "have been reading", ["'ve been reading", "’ve been reading"]),
  ("tf", "An exact number or amount ('three reports') usually signals the present perfect simple.", True),
  ("spot", "I have been reading three chapters this afternoon.", ["I", "have been reading", "three chapters", "this afternoon"], 1),
  ("mcq", "'Why are you out of breath?' — 'I ___.'", ["have been running", "have run", "run", "am run"], 0),
  ("gap", "They ___ (wait) for over an hour, and they're getting annoyed.", "have been waiting", ["'ve been waiting", "’ve been waiting"]),
  ("wb", "Unscramble the missing word: I have ___ finished the report — here it is.", "JUST"),
  ("mcq", "Which sentence focuses on the finished RESULT?", ["I've painted the kitchen.", "I've been painting the kitchen.", "I'm painting the kitchen.", "I was painting the kitchen."], 0),
  ("tf", "'I've been knowing her for years' is correct.", False),
  ("gap", "She ___ (already/finish) her part of the task.", "has already finished", ["'s already finished", "’s already finished"]),
  ("mcq", "How long ___ English?", ["have you been learning", "are you learning", "do you learn", "you have learnt"], 0),
])

quiz("b1-05", course=B1, n=5, lesson="lesson-05-past-perfect-simple-vs-continuous.html",
  name="Past Perfect Simple vs Past Perfect Continuous",
  structures="past perfect simple (had + past participle) vs past perfect continuous (had been + -ing); the past before the past",
  tags=["past-perfect", "past-perfect-continuous"], qs=[
  ("mcq", "When I arrived, the film ___.", ["had already started", "already starts", "has already started", "was already start"], 0),
  ("gap", "By 8pm, she ___ (finish) all her work.", "had finished", ["'d finished", "’d finished"]),
  ("mcq", "They ___ for two hours when the bus finally came.", ["had been waiting", "have been waiting", "are waiting", "will wait"], 0),
  ("tf", "'When I arrived, she left' means she had already gone before I got there.", False),
  ("spot", "He was out of breath because he has been running.", ["He was", "out of breath", "because he", "has been running"], 3),
  ("mcq", "By 6pm, she ___ three reports.", ["had written", "had been writing", "has written", "writes"], 0),
  ("gap", "He was nervous because he ___ (never/give) a speech before.", "had never given", ["'d never given", "’d never given"]),
  ("wb", "Unscramble the missing word: By the time I joined, she had ___ worked there for five years.", "ALREADY"),
  ("mcq", "Which sentence shows an activity still in progress up to a past moment?", ["She had been studying for hours before the test started.", "She had studied the whole book before the test.", "She studied before the test.", "She studies before every test."], 0),
  ("tf", "If you tell two past events in the order they happened, the past simple is usually enough.", True),
  ("gap", "The ground was wet because it ___ (rain) all night.", "had been raining", ["'d been raining", "’d been raining"]),
  ("mcq", "The past perfect simple is formed with…", ["had + past participle", "have + past participle", "was/were + -ing", "had + -ing"], 0),
])

quiz("b1-06", course=B1, n=6, lesson="lesson-06-future-forms.html",
  name="Future Forms: Will vs Going To vs Present Continuous",
  structures="will (decisions, promises, opinions) vs going to (evidence, plans) vs present continuous (fixed arrangements)",
  tags=["future-forms", "will", "going-to"], qs=[
  ("mcq", "Look out — that vase ___ fall!", ["is going to", "will", "is falling to", "falls"], 0),
  ("mcq", "Don't worry, I ___ fix it for you. (a decision made right now)", ["will", "am going to", "am fixing", "fix"], 0),
  ("gap", "We ___ (meet) the client at 11am — it's in both our calendars.", "are meeting", ["'re meeting", "’re meeting"]),
  ("tf", "'Going to' is used for predictions based on evidence you can see now.", True),
  ("spot", "Look at those clouds — it's going rain any minute.", ["Look at those clouds", "it's going rain", "any minute"], 1),
  ("mcq", "I've decided — I ___ retrain as a nurse next year.", ["am going to", "will", "retrain", "am retrain"], 0),
  ("wb", "Unscramble the missing word: I ___ help you with that — give me a second.", "WILL"),
  ("mcq", "Which sentence describes a fixed ARRANGEMENT?", ["I'm flying to Rome on Friday — I've got my ticket.", "I think I'll fly to Rome one day.", "Maybe I'll go to Rome.", "Rome will be hot."], 0),
  ("gap", "Look at those clouds — it's ___ to rain.", "going", []),
  ("tf", "'Will' is used for a decision made at the moment of speaking.", True),
  ("mcq", "I reckon the market ___ recover eventually.", ["will", "is recovering", "recovers", "is recover"], 0),
  ("gap", "I ___ (see) the dentist at 3pm on Friday — it's booked.", "am seeing", ["'m seeing", "’m seeing", "am going to see"]),
])
