from common import quiz, B1

quiz("b1-07", course=B1, n=7, lesson="lesson-07-future-perfect-vs-continuous.html",
  name="Future Perfect, Future Perfect Continuous & Future Continuous",
  structures="future perfect (will have + past participle), future perfect continuous (will have been + -ing), future continuous (will be + -ing); by vs at",
  tags=["future-perfect", "future-continuous"], qs=[
  ("mcq", "By next June, she ___ her degree.", ["will have finished", "will be finishing", "is finishing", "finishes"], 0),
  ("mcq", "This time tomorrow, we ___ on the beach.", ["will be relaxing", "will have relaxed", "relax", "are relaxed"], 0),
  ("gap", "By 2030, the company ___ (build) three new factories.", "will have built", []),
  ("tf", "'By 6pm' asks whether something will be finished in time; 'at 6pm' asks what will be happening at that moment.", True),
  ("spot", "By the time you read this letter, I will leave.", ["By the time", "you read", "this letter", "I will leave"], 3),
  ("mcq", "By Friday, I ___ on this project for a whole month.", ["will have been working", "will be working", "will work", "am working"], 0),
  ("wb", "Unscramble the missing word: Don't call at 9 — I'll be ___ dinner then.", "HAVING"),
  ("gap", "At 6pm, I ___ (finish) the report, so I'll still be busy.", "will be finishing", ["'ll be finishing", "’ll be finishing"]),
  ("mcq", "The future perfect continuous is formed with…", ["will have been + -ing", "will be + -ing", "will have + past participle", "will + base verb"], 0),
  ("tf", "'Will have + past participle' describes an action still in progress at a future moment.", False),
  ("mcq", "Don't call me at 8 — I ___ my presentation then.", ["will be giving", "will have given", "give", "am give"], 0),
  ("gap", "By the end of the year, they ___ (save) enough money for a house.", "will have saved", []),
])

quiz("b1-08", course=B1, n=8, lesson="lesson-08-modals-ability-permission-obligation.html",
  name="Modals of Ability, Permission, Obligation & Prohibition",
  structures="can/could/be able to/managed to; may; must/have to/had to; mustn't vs don't have to",
  tags=["modal-verbs", "obligation", "permission"], qs=[
  ("mcq", "You ___ finish it today — next week is fine too.", ["don't have to", "mustn't", "can't", "shouldn't to"], 0),
  ("mcq", "Visitors ___ park in the staff-only spaces.", ["mustn't", "don't have to", "needn't", "may"], 0),
  ("gap", "After months of trying, she finally ___ to pass the exam.", "managed", []),
  ("tf", "'Must' has no past form of its own, so we use 'had to' for past obligation.", True),
  ("spot", "All staff musted complete the training before the launch.", ["All staff", "musted", "complete the training", "before the launch"], 1),
  ("mcq", "She ___ read by the age of four. (general ability in the past)", ["could", "managed to", "was able", "must"], 0),
  ("wb", "Unscramble the missing word: Visitors ___ take photos in the lobby. (formal permission)", "MAY"),
  ("mcq", "We ___ leave early that day — the manager said it was fine.", ["were allowed to", "must", "had", "could to"], 0),
  ("tf", "'You mustn't wear a suit' and 'You don't have to wear a suit' mean the same thing.", False),
  ("gap", "I was ___ to fix it just in time.", "able", []),
  ("mcq", "Which sentence expresses a PROHIBITION?", ["You mustn't smoke inside the building.", "You don't have to smoke.", "You can smoke outside.", "You should stop smoking."], 0),
  ("gap", "Last year, we ___ (have to) work every Saturday.", "had to", []),
])

quiz("b1-09", course=B1, n=9, lesson="lesson-09-modals-deduction-speculation.html",
  name="Modals of Deduction & Speculation",
  structures="must be / can't be / might, could, may be; past: must have / can't have / might have + past participle",
  tags=["modal-verbs", "deduction", "speculation"], qs=[
  ("mcq", "She's wearing a wedding ring, so she ___ married.", ["must be", "can't be", "mustn't be", "should be"], 0),
  ("mcq", "He's on a beach in the photo, so he ___ at work right now.", ["can't be", "must be", "mustn't be", "has to be"], 0),
  ("gap", "The office was spotless, so someone ___ cleaned it overnight.", "must have", []),
  ("tf", "The negative of deductive 'must be' is 'mustn't be'.", False),
  ("spot", "He was on a plane at the time, so he must have sent that email himself.", ["He was", "on a plane", "must have sent", "himself"], 2),
  ("mcq", "I'm not sure, but it ___ be a scam email.", ["could", "must", "can't", "has to"], 0),
  ("wb", "Unscramble the missing word: She ___ be running late — let's wait five more minutes.", "MIGHT"),
  ("mcq", "Her coat's gone, so she ___ already.", ["must have left", "must leave", "can't have left", "should left"], 0),
  ("tf", "'Might', 'could' and 'may' all express genuine uncertainty.", True),
  ("gap", "He ___ have finished already — he only started an hour ago.", "can't", ["couldn't", "can’t", "couldn’t", "cannot"]),
  ("mcq", "Which sentence is a confident NEGATIVE deduction about the past?", ["She can't have seen us.", "She mustn't have seen us.", "She might have seen us.", "She must have seen us."], 0),
  ("gap", "The car's engine is still warm, so someone ___ have driven it recently.", "must", []),
])

quiz("b1-10", course=B1, n=10, lesson="lesson-10-modal-perfect.html",
  name="Modal Perfect: Should Have, Could Have, Would Have",
  structures="should/shouldn't have (regret, criticism), could have (missed opportunity), would have (hypothetical past) + past participle",
  tags=["modal-perfect", "should-have", "could-have"], qs=[
  ("mcq", "I ___ studied harder for that exam — I failed.", ["should have", "must have", "can't have", "would have"], 0),
  ("mcq", "You ___ borrowed my car without asking — that was out of line.", ["shouldn't have", "could have", "must have", "would have"], 0),
  ("gap", "She ___ taken the promotion, but she turned it down for personal reasons.", "could have", []),
  ("tf", "'She could have won the race' can describe a real opportunity that didn't happen.", True),
  ("spot", "I would have called, but I didn't had your number.", ["I would have called", "but", "I didn't had", "your number"], 2),
  ("mcq", "'I would have called, but I didn't have your number.' This describes…", ["a hypothetical past outcome", "a confident guess", "a present habit", "a future plan"], 0),
  ("wb", "Unscramble the missing word: You should have ___ me sooner!", "TOLD"),
  ("gap", "He ___ have said that in the meeting — it upset everyone.", "shouldn't", ["should not", "shouldn’t"]),
  ("mcq", "The modal perfect is formed with…", ["modal + have + past participle", "modal + has + past participle", "modal + had + past participle", "modal + been + base verb"], 0),
  ("tf", "'You should have locked the door' means you locked it, and that was a mistake.", False),
  ("mcq", "You ___ told me it was your birthday — I'd have bought you a present!", ["could have", "must have", "can't have", "would"], 0),
  ("spot", "We should have leave earlier — we missed the train.", ["We", "should have leave", "earlier", "missed the train"], 1),
])

quiz("b1-11", course=B1, n=11, lesson="lesson-11-passive-voice.html",
  name="Passive Voice: Core Forms Across Tenses",
  structures="be + past participle in every tense (is made, was built, has been written, is being built, will be announced, must be submitted); get-passive",
  tags=["passive-voice"], qs=[
  ("mcq", "The bridge ___ in 1889.", ["was built", "built", "is built", "has built"], 0),
  ("gap", "The results ___ (announce) tomorrow.", "will be announced", []),
  ("mcq", "This form ___ by Friday.", ["must be submitted", "must submit", "must submitted", "must be submit"], 0),
  ("tf", "In a passive sentence, the 'by' phrase (who did it) is optional.", True),
  ("spot", "The cake was make by my grandmother.", ["The cake", "was make", "by", "my grandmother"], 1),
  ("mcq", "The report ___ yet.", ["hasn't been written", "hasn't written", "isn't wrote", "hasn't been write"], 0),
  ("wb", "Unscramble the missing word: My bike got ___ yesterday.", "STOLEN"),
  ("gap", "Tea ___ (grow) in many countries.", "is grown", []),
  ("mcq", "The roof must ___ by the storm.", ["have been damaged", "have damaged", "been damaged", "be damage"], 0),
  ("tf", "'Mistakes were made' can be used to avoid naming who made them.", True),
  ("gap", "The new station ___ (build) at the moment.", "is being built", []),
  ("mcq", "Three arrests ___ so far.", ["have been made", "have made", "were make", "has been made"], 0),
])

quiz("b1-12", course=B1, n=12, lesson="lesson-12-passive-extensions.html",
  name="Passive Extensions: Reporting Structures & Causative",
  structures="It is said/thought that…; subject + is said/believed to (have) + verb; causative have/get something done",
  tags=["passive-voice", "reporting-structures", "causative"], qs=[
  ("mcq", "___ that the company will announce layoffs next week.", ["It is rumoured", "It rumours", "It is rumour", "It rumoured"], 0),
  ("mcq", "She is said ___ in intelligence before becoming a teacher.", ["to have worked", "to work", "that she worked", "having worked"], 0),
  ("gap", "We ___ our kitchen renovated last month.", "had", ["got"]),
  ("tf", "'I had my car repaired' means I repaired it myself.", False),
  ("spot", "She is thought that she wrote the letter herself.", ["She", "is thought", "that she wrote", "the letter herself"], 2),
  ("mcq", "He ___ his suit dry-cleaned before the interview.", ["had", "made", "did", "let"], 0),
  ("wb", "Unscramble the missing word: It is ___ that the building is haunted.", "SAID"),
  ("gap", "At the time, it ___ believed that the experiment was harmless.", "was", []),
  ("mcq", "Which is the more informal alternative to 'have something done'?", ["get something done", "make something done", "do something done", "let something done"], 0),
  ("tf", "'He is believed to be living abroad' and 'It is believed that he is living abroad' report the same claim.", True),
  ("gap", "I need to get my hair ___ (cut) before the wedding.", "cut", []),
  ("mcq", "The painting is thought ___ stolen in the 1990s.", ["to have been", "to be", "that it was", "being"], 0),
])
