from common import quiz, B1

quiz("b1-13", course=B1, n=13, lesson="lesson-13-conditionals-zero-first.html",
  name="Conditionals: Zero & First",
  structures="zero conditional (if + present simple, present simple) and first conditional (if + present simple, will + verb); unless",
  tags=["conditionals", "zero-conditional", "first-conditional"], qs=[
  ("mcq", "Water ___ if it is cooled below 0°C.", ["freezes", "is freezing", "would freeze", "froze"], 0),
  ("mcq", "If she doesn't hurry, she ___ the train.", ["will miss", "misses", "would miss", "missed"], 0),
  ("gap", "If it ___ (rain) this weekend, we'll postpone the trip.", "rains", []),
  ("tf", "In zero and first conditionals, 'will' never goes in the if-clause.", True),
  ("spot", "If you will need help, just call me.", ["If you", "will need", "help", "just call me"], 1),
  ("mcq", "If you mix red and blue, you ___ purple.", ["get", "got", "would get", "had got"], 0),
  ("wb", "Unscramble the missing word: Plants die if ___ don't get enough light.", "THEY"),
  ("mcq", "Which sentence is a FIRST conditional?", ["If it rains tomorrow, we'll cancel the picnic.", "If you heat water to 100°C, it boils.", "If I were you, I'd go.", "If I had known, I'd have told you."], 0),
  ("gap", "If you ___ (not/water) plants, they die.", "don't water", ["do not water", "don’t water"]),
  ("tf", "In a conditional sentence, the if-clause must always come first.", False),
  ("gap", "We'll miss the start ___ we leave now. (= if we don't leave now)", "unless", []),
  ("mcq", "If I finish work early, I ___ you.", ["will call", "call", "would call", "called"], 0),
])

quiz("b1-14", course=B1, n=14, lesson="lesson-14-second-conditional.html",
  name="Second Conditional",
  structures="second conditional (if + past simple, would/could/might + verb); If I were you",
  tags=["conditionals", "second-conditional"], qs=[
  ("mcq", "If I ___ rich, I would buy a huge house.", ["were", "am", "will be", "would be"], 0),
  ("mcq", "If you study harder, you ___ pass the exam. (a real possibility)", ["will", "would", "did", "had"], 0),
  ("gap", "If she ___ (know) the truth, she would tell someone.", "knew", []),
  ("tf", "In the second conditional, the past-simple if-clause is about the past.", False),
  ("spot", "If I would have more time, I'd learn Italian.", ["If I", "would have", "more time", "I'd learn Italian"], 1),
  ("mcq", "If I were you, I ___ apologise.", ["would", "will", "am", "did"], 0),
  ("wb", "Unscramble the missing word: If I ___ you, I'd take the job.", "WERE"),
  ("mcq", "Which sentence is a SECOND conditional?", ["If I won the lottery, I would travel the world.", "If it rains, I will stay home.", "Ice melts if you leave it in the sun.", "If I had seen it, I would have told you."], 0),
  ("gap", "If we had a bigger flat, we ___ (can) invite more friends.", "could", []),
  ("tf", "'Could' and 'might' can replace 'would' in the result clause.", True),
  ("spot", "If she lived closer, she will visit more often.", ["If she", "lived closer", "she will visit", "more often"], 2),
  ("mcq", "What would you do if you ___ a million dollars?", ["found", "find", "will find", "would find"], 0),
])

quiz("b1-15", course=B1, n=15, lesson="lesson-15-third-conditional.html",
  name="Third Conditional",
  structures="third conditional (if + past perfect, would/could/might have + past participle); contractions I'd / I'd have",
  tags=["conditionals", "third-conditional"], qs=[
  ("mcq", "If I ___ that, I would have told you.", ["had known", "knew", "have known", "would know"], 0),
  ("mcq", "If we had left earlier, we ___ the train.", ["would have caught", "would catch", "will catch", "caught"], 0),
  ("gap", "If she ___ (ask), I would have helped her.", "had asked", ["'d asked", "’d asked"]),
  ("tf", "'If I had studied harder, I would have passed' means I didn't study harder and I didn't pass.", True),
  ("spot", "If I studied harder last year, I would have passed the exam.", ["If I", "studied", "last year", "would have passed"], 1),
  ("mcq", "In 'I'd have called you', 'I'd' stands for…", ["I would", "I had", "I did", "I should"], 0),
  ("wb", "Unscramble the missing word: If you had told me, I ___ have come.", "WOULD"),
  ("gap", "If they had trained more, they might ___ (win).", "have won", []),
  ("mcq", "Third conditional: if + past perfect, + …", ["would have + past participle", "would + base verb", "will + base verb", "present simple"], 0),
  ("tf", "In 'If I'd known…', 'I'd' stands for 'I would'.", False),
  ("mcq", "If he hadn't missed the bus, he ___ late for the interview.", ["wouldn't have been", "won't be", "wasn't", "hadn't been"], 0),
  ("gap", "We ___ (not/get) lost if we had taken a map.", "wouldn't have got", ["would not have got", "wouldn't have gotten", "would not have gotten", "wouldn’t have got", "wouldn’t have gotten"]),
])

quiz("b1-16", course=B1, n=16, lesson="lesson-16-mixed-conditionals.html",
  name="Mixed Conditionals",
  structures="past condition → present result (if + past perfect, would + verb); ongoing condition → past result (if + past simple, would have + past participle)",
  tags=["conditionals", "mixed-conditionals"], qs=[
  ("mcq", "If I ___ harder at school, I would have a better job now.", ["had studied", "studied", "would study", "study"], 0),
  ("mcq", "If she were more confident, she ___ for the promotion last year.", ["would have applied", "would apply", "will apply", "applied"], 0),
  ("gap", "If he had taken the earlier flight, he ___ (be) here by now.", "would be", ["'d be", "’d be"]),
  ("tf", "'If I had learned to swim as a child, I wouldn't be afraid of water now' mixes a past condition with a present result.", True),
  ("spot", "If I had taken that job, I would have been rich now.", ["If I", "had taken that job", "would have been", "rich now"], 2),
  ("mcq", "Which sentence mixes an ONGOING condition with a PAST result?", ["If she weren't so shy, she would have spoken up yesterday.", "If she had spoken up, she would be happier now.", "If she speaks up, she'll be heard.", "If she spoke up, she'd be heard."], 0),
  ("wb", "Unscramble the missing word: If I hadn't missed the train, I'd be at ___ now.", "HOME"),
  ("gap", "If they weren't so private, they ___ shared the news already.", "would have", ["'d have", "’d have"]),
  ("tf", "In a mixed conditional, both clauses must refer to the same time.", False),
  ("mcq", "If I ___ so afraid of flying (and I still am!), I would have visited you last summer.", ["weren't", "am not", "won't be", "don't be"], 0),
  ("mcq", "If you had listened to me, we ___ in this mess now.", ["wouldn't be", "wouldn't have been", "won't be", "aren't"], 0),
  ("gap", "If she ___ (not/move) abroad, she would still be living with her parents.", "hadn't moved", ["had not moved", "hadn’t moved"]),
])

quiz("b1-17", course=B1, n=17, lesson="lesson-17-wish-if-only.html",
  name="Wish / If Only",
  structures="wish/if only + past simple (present regret), + past perfect (past regret), + would (someone else's behaviour)",
  tags=["wish", "if-only", "regret"], qs=[
  ("mcq", "I wish I ___ taller.", ["were", "am", "would be", "will be"], 0),
  ("mcq", "I wish I ___ harder at school — I'd have more options now.", ["had studied", "would study", "study", "will study"], 0),
  ("gap", "I wish you ___ stop interrupting me!", "would", []),
  ("tf", "'Wish + would' is usually used about your own behaviour.", False),
  ("spot", "I wish I would have listened to your advice.", ["I wish", "I would have listened", "to your advice"], 1),
  ("mcq", "If only she ___ the truth sooner.", ["had known", "knows", "will know", "has known"], 0),
  ("wb", "Unscramble the missing word: I wish it would stop ___!", "RAINING"),
  ("mcq", "'I wish I had a car' expresses regret about…", ["the present", "the past", "a future plan", "someone else's habit"], 0),
  ("gap", "I wish I ___ (not/say) that to her yesterday.", "hadn't said", ["had not said", "hadn’t said"]),
  ("tf", "'If only' is a more emphatic, emotional alternative to 'I wish'.", True),
  ("mcq", "I wish my neighbours ___ so much noise every night.", ["wouldn't make", "don't make", "won't make", "hadn't make"], 0),
  ("gap", "I wish I ___ (can) speak Japanese.", "could", []),
])

quiz("b1-18", course=B1, n=18, lesson="lesson-18-reported-speech.html",
  name="Reported Speech",
  structures="backshift in reported statements (said that…), reported questions (asked where/if…), commands (told someone to…)",
  tags=["reported-speech"], qs=[
  ("mcq", "'I am tired,' she said. → She said she ___ tired.", ["was", "will be", "were", "is being"], 0),
  ("mcq", "'Where do you live?' he asked. → He asked where I ___.", ["lived", "did live", "do live", "was live"], 0),
  ("gap", "'Close the door,' she said. → She told him ___ close the door.", "to", []),
  ("tf", "Reported questions use normal statement word order and no question mark.", True),
  ("spot", "She asked me where did I work.", ["She asked me", "where", "did I work"], 2),
  ("mcq", "'I will help you,' he said. → He said he ___ help me.", ["would", "will", "had", "was"], 0),
  ("wb", "Unscramble the missing word: He asked me ___ I was coming to the party.", "WHETHER"),
  ("gap", "'Don't be late,' the manager said. → The manager told us ___ to be late.", "not", []),
  ("mcq", "Which sentence is correct?", ["She told me that she was leaving.", "She said me that she was leaving.", "She told that she was leaving.", "She said to me she is leave."], 0),
  ("tf", "In reported speech, 'that' after 'said' can often be left out.", True),
  ("gap", "'I have finished,' he said. → He said he ___ finished.", "had", []),
  ("mcq", "'Can you help me?' she asked. → She asked me if I ___ help her.", ["could", "can to", "am able", "will to"], 0),
])

quiz("b1-19", course=B1, n=19, lesson="lesson-19-relative-clauses.html",
  name="Relative Clauses: Defining vs Non-defining",
  structures="defining vs non-defining relative clauses; who, which, that, whose, whom, where, when; commas",
  tags=["relative-clauses"], qs=[
  ("mcq", "The woman ___ called earlier is my sister.", ["who", "which", "whose", "where"], 0),
  ("mcq", "My car, ___ is ten years old, still runs well.", ["which", "that", "who", "what"], 0),
  ("gap", "This is the house ___ I grew up.", "where", []),
  ("tf", "Non-defining relative clauses are separated by commas and can't use 'that'.", True),
  ("spot", "My brother, that lives in London, called me yesterday.", ["My brother", "that", "lives in London", "called me yesterday"], 1),
  ("mcq", "In 'The book (that) I borrowed was excellent', 'that' can be dropped because…", ["it's the object of the clause", "it's the subject of the clause", "the clause is non-defining", "'that' can always be dropped"], 0),
  ("wb", "Unscramble the missing word: That's the colleague ___ laptop was stolen.", "WHOSE"),
  ("gap", "I'll never forget the day ___ we met.", "when", ["that"]),
  ("mcq", "'My brother, who lives in London, called.' This means…", ["I have one brother; the clause is extra information.", "I have several brothers; the clause says which one.", "My brother called from London.", "My brother doesn't live in London."], 0),
  ("tf", "Defining relative clauses are always separated by commas.", False),
  ("gap", "I have a neighbour ___ lends me her tools.", "who", ["that"]),
  ("mcq", "The man to ___ I spoke was very helpful. (formal)", ["whom", "who", "which", "that"], 0),
])

quiz("b1-20", course=B1, n=20, lesson="lesson-20-gerunds-vs-infinitives.html",
  name="Gerunds vs Infinitives",
  structures="verb + -ing (enjoy, avoid) vs verb + to-infinitive (decide, want); preposition + -ing; remember/stop/forget + -ing vs to",
  tags=["gerunds", "infinitives", "verb-patterns"], qs=[
  ("mcq", "She enjoys ___ before bed.", ["reading", "to read", "read", "to reading"], 0),
  ("mcq", "They decided ___ to a new city.", ["to move", "moving", "move", "to moving"], 0),
  ("gap", "He stopped ___ (smoke) five years ago.", "smoking", []),
  ("tf", "'I remember locking the door' is about a memory of a past action.", True),
  ("spot", "She avoided to answer the question.", ["She", "avoided", "to answer", "the question"], 2),
  ("mcq", "I'm interested ___ French.", ["in learning", "to learning", "learn", "on learning"], 0),
  ("wb", "Unscramble the missing word: I called to ___ for being late.", "APOLOGISE"),
  ("gap", "Don't forget ___ (lock) the door when you leave.", "to lock", []),
  ("mcq", "Which verb is followed by a gerund (-ing)?", ["avoid", "want", "decide", "hope"], 0),
  ("tf", "'He stopped to smoke' and 'He stopped smoking' mean the same thing.", False),
  ("gap", "___ (swim) is great exercise.", "Swimming", []),
  ("mcq", "It's important ___ on time.", ["to arrive", "arriving", "arrive", "for arrive"], 0),
])

quiz("b1-21", course=B1, n=21, lesson="lesson-21-articles-determiners.html",
  name="Articles & Determiners",
  structures="a/an, the, zero article; quantifiers (much, many, a few, a little)",
  tags=["articles", "determiners", "quantifiers"], qs=[
  ("mcq", "I saw ___ dog in the park.", ["a", "the", "an", "(no article)"], 0),
  ("mcq", "I saw a dog in the park. ___ dog started barking loudly.", ["The", "A", "An", "(no article)"], 0),
  ("gap", "She's ___ honest person.", "an", []),
  ("tf", "'Cheetahs are fast animals' is correct as a general statement about cheetahs as a species.", True),
  ("spot", "He's a university lecturer and a expert in AI.", ["He's", "a university lecturer", "a expert", "in AI"], 2),
  ("mcq", "I have ___ time to help — about ten minutes.", ["a little", "little", "a few", "few"], 0),
  ("wb", "Unscramble the missing word: There isn't ___ milk left — we need to buy some.", "MUCH"),
  ("gap", "There are only ___ tickets left, so book now. (a small number)", "a few", []),
  ("mcq", "Which is correct?", ["I saw a dog.", "I saw dog.", "I saw the a dog.", "I saw an dog."], 0),
  ("tf", "We choose 'a' or 'an' based on spelling, not sound.", False),
  ("gap", "___ sun rises in the east.", "The", []),
  ("mcq", "How ___ people came to the meeting?", ["many", "much", "little", "a little"], 0),
])

quiz("b1-22", course=B1, n=22, lesson="lesson-22-discourse-emphasis-capstone.html",
  name="Linking Words, Hedging & Cleft Sentences",
  structures="linking words (however, therefore, moreover), hedging (seem, appear, may), cleft sentences (It was… that / What… is)",
  tags=["linking-words", "hedging", "cleft-sentences"], qs=[
  ("mcq", "The plan was risky. ___, it relied on outdated data.", ["Moreover", "However", "Therefore", "In contrast"], 0),
  ("mcq", "The team had plenty of experience. ___, they rarely challenged each other.", ["However", "Therefore", "Moreover", "As a result"], 0),
  ("gap", "No one raised concerns. ___, the flawed plan went ahead.", "Therefore", ["As a result", "Consequently", "Thus", "So"]),
  ("tf", "Hedging language makes a claim sound more careful and less absolute.", True),
  ("gap", "___ was groupthink that caused the failure.", "It", []),
  ("mcq", "Which sentence is hedged?", ["The results seem to suggest a link.", "The results prove a link.", "There is definitely a link.", "The link is obvious."], 0),
  ("wb", "Unscramble the missing word: What the team needed ___ an outside opinion.", "WAS"),
  ("spot", "What caused the failure were groupthink.", ["What", "caused the failure", "were", "groupthink"], 2),
  ("mcq", "'What we need is more time.' This is a…", ["wh-cleft", "it-cleft", "question", "passive"], 0),
  ("tf", "'However' and 'therefore' do the same job: both introduce a result.", False),
  ("mcq", "Which word introduces an ADDITIONAL point?", ["Furthermore", "Nevertheless", "Consequently", "Although"], 0),
  ("gap", "The data ___ to support this idea, but more research is needed. (a hedging verb)", "appear", ["appears", "seem", "seems", "tend", "tends"]),
])
