from common import quiz, B2

quiz("b2-01", course=B2, n=1, lesson="lesson-01-narrative-tenses.html",
  name="Narrative Tenses in Extended Storytelling",
  structures="past simple (story spine), past continuous (background), past perfect (flashbacks)",
  tags=["narrative-tenses", "past-perfect", "past-continuous"], qs=[
  ("mcq", "While the CEO ___ her speech, the lights suddenly went out.", ["was giving", "gave", "had given", "has given"], 0),
  ("mcq", "By the time the investors arrived, the team ___ the whole presentation.", ["had rehearsed", "rehearses", "has rehearsed", "is rehearsing"], 0),
  ("gap", "He realised he ___ (leave) his badge at home, so he had to sign in as a visitor.", "had left", ["'d left", "’d left"]),
  ("tf", "In a story, every earlier action needs the past perfect, even in a simple sequence.", False),
  ("mcq", "She opened the email, read it twice, then ___ her manager.", ["called", "was calling", "had called", "calls"], 0),
  ("spot", "I was walking to work when I was seeing an old friend.", ["I was walking", "to work", "when", "I was seeing"], 3),
  ("wb", "Unscramble the missing word: By the time she arrived, everyone had ___.", "LEFT"),
  ("gap", "It ___ (rain) heavily when the meeting started.", "was raining", []),
  ("mcq", "In a story, which tense usually sets the background scene?", ["past continuous", "past simple", "past perfect", "present perfect"], 0),
  ("tf", "The past simple usually moves the main sequence of events forward.", True),
  ("mcq", "When we got to the station, the train ___, so we waited an hour for the next one.", ["had left", "has left", "leaves", "have left"], 0),
  ("gap", "She left the office early because she ___ (finish) her work.", "had finished", ["'d finished", "’d finished"]),
])

quiz("b2-02", course=B2, n=2, lesson="lesson-02-used-to-vs-would.html",
  name="Used To vs Would for Past Habits",
  structures="used to + verb (past habits and states) vs would + verb (repeated past actions only); didn't use to",
  tags=["used-to", "would", "past-habits"], qs=[
  ("mcq", "She ___ a lot of money before she changed careers.", ["used to earn", "would earn", "was used to earn", "use to earn"], 0),
  ("mcq", "Every Friday, my father ___ us to the cinema.", ["would take", "was taking", "is used to take", "takes"], 0),
  ("gap", "I ___ believe in ghosts when I was a child.", "used to", []),
  ("tf", "'Would' can describe past states, e.g. 'I would own a motorbike.'", False),
  ("spot", "When I was young, I would have very long hair.", ["When I was young", "I", "would have", "very long hair"], 2),
  ("mcq", "Which sentence is correct for a past STATE?", ["I used to live in Kraków.", "I would live in Kraków.", "I was used to live in Kraków.", "I use to live in Kraków."], 0),
  ("wb", "Unscramble the missing word: We would ___ hours just talking about nothing.", "SPEND"),
  ("tf", "For repeated past actions, 'used to' and 'would' are usually interchangeable.", True),
  ("gap", "Did you ___ to play the piano as a child?", "use", []),
  ("mcq", "'I'm used to working late' means…", ["Working late is normal for me now.", "I worked late in the past, but not now.", "I will start working late.", "I refuse to work late."], 0),
  ("spot", "She didn't used to like coffee.", ["She", "didn't used to", "like", "coffee"], 1),
  ("mcq", "Which sentence is NOT correct?", ["I would believe in Father Christmas as a child.", "I used to believe in Father Christmas as a child.", "We would go camping every summer.", "We used to go camping every summer."], 0),
])

quiz("b2-03", course=B2, n=3, lesson="lesson-03-future-in-the-past.html",
  name="Future in the Past + Future Perfect Continuous",
  structures="was/were going to and would (future seen from the past) vs will have been + -ing (duration up to a future point)",
  tags=["future-in-the-past", "future-perfect-continuous"], qs=[
  ("mcq", "We ___ have a picnic, but it started raining.", ["were going to", "are going to", "will", "would have"], 0),
  ("mcq", "By 2027, she ___ this company for two decades.", ["will have been running", "will run", "runs", "is running"], 0),
  ("gap", "He told us he ___ resign at the end of the year.", "would", []),
  ("tf", "'Was going to' often suggests that the plan didn't happen.", True),
  ("spot", "She said she will call me later, but she never did.", ["She said", "she will call", "me later", "she never did"], 1),
  ("mcq", "By the time you land, I ___ for you at the airport for an hour.", ["will have been waiting", "will wait", "am waiting", "was waiting"], 0),
  ("wb", "Unscramble the missing word: We were ___ to move to Berlin, but the job offer fell through.", "GOING"),
  ("gap", "By June, I ___ (work) here for ten years.", "will have been working", ["will have worked"]),
  ("mcq", "The future perfect continuous focuses on…", ["the duration of an action up to a future point", "a plan that was cancelled", "a single finished action", "a present habit"], 0),
  ("tf", "The future perfect continuous usually implies that a plan was cancelled.", False),
  ("mcq", "I thought the meeting ___ at 10, but it started at 9.", ["would start", "will start", "starts", "has started"], 0),
  ("gap", "I knew the project ___ (be) difficult, but not this difficult.", "would be", ["was going to be"]),
])

quiz("b2-04", course=B2, n=4, lesson="lesson-04-academic-hedging.html",
  name="Academic Hedging: Seem To, Appear To, Tend To, Be Likely To",
  structures="seem to / appear to (evidence-based caution), tend to (general pattern), be likely to (future probability)",
  tags=["hedging", "academic-english"], qs=[
  ("mcq", "The results ___ support the original hypothesis.", ["appear to", "are appearing to", "appear", "appearing to"], 0),
  ("mcq", "Remote workers ___ report higher job satisfaction, though not universally.", ["tend to", "are tending to", "tend", "tending"], 0),
  ("gap", "Given current trends, prices are ___ to rise further next quarter.", "likely", []),
  ("tf", "'Tend to' describes a general pattern, not a universal rule.", True),
  ("spot", "She is seeming to have misunderstood the instructions.", ["She", "is seeming", "to have misunderstood", "the instructions"], 1),
  ("mcq", "Which claim is the most cautious?", ["The data seems to suggest a correlation.", "The data proves a correlation.", "The data clearly shows a correlation.", "There is a correlation."], 0),
  ("wb", "Unscramble the missing word: Junior staff ___ to ask more questions.", "TEND"),
  ("mcq", "Which sentence is a forward-looking PROBABILITY?", ["Costs are likely to rise next year.", "The plan seems to be succeeding.", "Junior staff tend to ask more questions.", "The results appear to confirm it."], 0),
  ("tf", "'The results tend to confirm the theory' is the best way to describe one single observation.", False),
  ("gap", "The plan ___ to be succeeding so far.", "seems", ["appears"]),
  ("mcq", "Hedging is used mainly to…", ["avoid overstating a claim you can't fully prove", "make a sentence longer", "hide the main point", "sound less formal"], 0),
  ("gap", "It is ___ that the trend will continue. (= probable)", "likely", []),
])

quiz("b2-05", course=B2, n=5, lesson="lesson-05-neednt-have.html",
  name="Needn't Have vs Didn't Need To",
  structures="needn't have + past participle (it happened, but was unnecessary) vs didn't need to + verb (it wasn't necessary)",
  tags=["neednt-have", "didnt-need-to", "modal-verbs"], qs=[
  ("mcq", "She ___ rushed — the meeting was cancelled, but she'd already left.", ["needn't have", "didn't need to", "mustn't have", "couldn't have"], 0),
  ("mcq", "We ___ apply for a visa — our stay was under 90 days.", ["didn't need to", "needn't have", "mustn't", "hadn't to"], 0),
  ("gap", "I ___ have worried — everything went perfectly.", "needn't", ["need not", "needn’t"]),
  ("tf", "'I needn't have bought a gift' means I bought one, but it wasn't necessary.", True),
  ("spot", "I needn't have booked a table, so I didn't.", ["I", "needn't have booked", "a table", "so I didn't"], 1),
  ("mcq", "'I didn't need to book a table' tells us…", ["booking wasn't necessary", "I booked a table for nothing", "I forgot to book", "booking was forbidden"], 0),
  ("wb", "Unscramble the missing word: He needn't have ___ it twice — I understood the first time.", "EXPLAINED"),
  ("gap", "They ___ to change the schedule at all — everyone was already free.", "didn't need", ["did not need", "didn’t need"]),
  ("mcq", "'Needn't have' is followed by…", ["a past participle", "a base verb", "an -ing form", "a to-infinitive"], 0),
  ("tf", "'Needn't have' can describe an action that never happened.", False),
  ("mcq", "You ___ cooked so much food — only three people came.", ["needn't have", "didn't need to", "mustn't have", "shouldn't to"], 0),
  ("tf", "'We didn't need to take a taxi' can describe a situation where we simply walked instead.", True),
])

quiz("b2-06", course=B2, n=6, lesson="lesson-06-deduction-continuous.html",
  name="Deduction With Continuous Aspect",
  structures="must / can't / might + have been + -ing (deduction about an action in progress) vs + have + past participle (completed action)",
  tags=["deduction", "modal-verbs", "continuous-aspect"], qs=[
  ("mcq", "The lights were on — someone ___ working late.", ["must have been", "must be", "must have", "can't have"], 0),
  ("mcq", "He's out of breath — he ___ running.", ["must have been", "must have", "must", "can't have been"], 0),
  ("gap", "They ___ have been arguing — I could hear raised voices through the wall.", "must", []),
  ("tf", "'He must have been knowing about the change' is correct.", False),
  ("spot", "She can't have been sleep — the light was still on.", ["She", "can't have been", "sleep", "the light was still on"], 2),
  ("mcq", "'He must have been sleeping when we called' means…", ["sleeping was in progress when we called", "he slept once and then finished", "he is sleeping now", "he was obliged to sleep"], 0),
  ("wb", "Unscramble the missing word: She ___ have been joking — surely she wasn't serious.", "MUST"),
  ("gap", "He might have ___ (drive) when you called — that's why he didn't answer.", "been driving", []),
  ("mcq", "Continuous deduction forms are built with…", ["modal + have been + -ing", "modal + being + past participle", "modal + have + past participle", "modal + been + base verb"], 0),
  ("tf", "'She must have left already' is a deduction about a completed action.", True),
  ("mcq", "He ___ about the change — it was in every email.", ["must have known", "must have been knowing", "must know been", "must be knowing"], 0),
  ("gap", "You ___ have been listening — I just explained that!", "can't", ["couldn't", "can’t", "couldn’t", "cannot"]),
])

quiz("b2-07", course=B2, n=7, lesson="lesson-07-inversion-conditionals.html",
  name="Inversion in Conditionals",
  structures="Were I (to)… / Had I known… / Should you… — formal conditionals without 'if'; negative forms (Had I not…)",
  tags=["conditionals", "inversion", "formal-english"], qs=[
  ("mcq", "___ the client sooner, we could have avoided the misunderstanding.", ["Had we contacted", "We had contacted", "If had we contacted", "Have we contacted"], 0),
  ("mcq", "___ you need anything during the audit, my door is always open.", ["Should", "Would", "Will", "Had"], 0),
  ("gap", "___ I in your position, I'd renegotiate the whole contract.", "Were", []),
  ("tf", "'Had I known' and 'If I had known' mean the same thing — only the register changes.", True),
  ("spot", "Hadn't I seen the email, I would have missed the deadline.", ["Hadn't I seen", "the email", "would have missed", "the deadline"], 0),
  ("mcq", "___ I to resign, the project would stall.", ["Were", "Was", "Had", "Should"], 0),
  ("wb", "Unscramble the missing word: ___ the merger fall through, shareholders would need reassurance.", "SHOULD"),
  ("gap", "Were she ___ accept the offer, the whole team would restructure.", "to", []),
  ("mcq", "Which is the correct NEGATIVE inversion?", ["Were I not to attend, …", "Weren't I to attend, …", "Were not I to attend, …", "I weren't to attend, …"], 0),
  ("tf", "Conditional inversion replaces the main clause, not the if-clause.", False),
  ("mcq", "'Should the client object, escalate to the manager' means…", ["If the client objects, escalate to the manager.", "The client ought to object.", "The client objected, so escalate.", "Unless the client objects, escalate."], 0),
  ("gap", "___ she called first, we would have prepared better.", "Had", []),
])
