from common import quiz, B2

quiz("b2-08", course=B2, n=8, lesson="lesson-08-conditional-alternatives.html",
  name="Conditional Alternatives to If",
  structures="provided (that), as long as, unless (= if…not), suppose/supposing, on condition that",
  tags=["conditionals", "unless", "provided-that"], qs=[
  ("mcq", "You can take the afternoon off, ___ you finish the report first.", ["as long as", "unless", "otherwise", "but for"], 0),
  ("mcq", "We won't renew the contract ___ the terms improve.", ["unless", "provided that", "as long as", "suppose"], 0),
  ("gap", "The vendor agreed to the deadline on ___ that we paid a deposit upfront.", "condition", []),
  ("tf", "'Unless' means 'if … not'.", True),
  ("spot", "Unless you don't finish the report, you can't leave.", ["Unless", "you don't finish", "the report", "you can't leave"], 1),
  ("mcq", "___ the client calls before Friday — what should I tell them?", ["Suppose", "Unless", "Provided", "Otherwise"], 0),
  ("wb", "Unscramble the missing word: We'll sign the deal, ___ that the price stays fixed.", "PROVIDED"),
  ("gap", "You can borrow my car as long as you ___ (bring) it back by six.", "bring", []),
  ("tf", "After 'provided that', we use 'will' for future meaning: 'provided that it will arrive on time'.", False),
  ("mcq", "Which linker sounds most like a formal, negotiated term?", ["on condition that", "suppose", "as long as", "if"], 0),
  ("mcq", "'Unless you object, we'll proceed as planned' means we'll proceed…", ["if you don't object", "only if you object", "whether or not you object", "after you object"], 0),
  ("mcq", "I'll lend you the money ___ you pay me back by Friday.", ["provided that", "unless", "otherwise", "suppose"], 0),
])

quiz("b2-09", course=B2, n=9, lesson="lesson-09-hypothetical-without-if.html",
  name="Hypothetical Meaning Without If",
  structures="otherwise + would/will; but for + noun phrase; without + -ing — conditionals hidden inside connectors",
  tags=["conditionals", "otherwise", "but-for"], qs=[
  ("mcq", "Book your ticket now; ___ the price will go up tomorrow.", ["otherwise", "but for", "without", "unless"], 0),
  ("mcq", "___ the investor's last-minute support, the startup would have folded.", ["But for", "Otherwise", "Unless", "Provided"], 0),
  ("gap", "She signed the contract ___ reading the fine print.", "without", []),
  ("tf", "'But for' is followed by a noun phrase, not a full clause.", True),
  ("spot", "But for she helped us, we would have failed.", ["But for", "she helped us", "we would have failed"], 1),
  ("mcq", "'We left early; otherwise, we would have missed the flight' means…", ["If we hadn't left early, we would have missed it.", "We missed the flight anyway.", "We didn't leave early.", "We will miss the flight."], 0),
  ("wb", "Unscramble the missing word: We backed up the files; ___ we would have lost everything.", "OTHERWISE"),
  ("gap", "But ___ her quick thinking, the deal would have collapsed.", "for", []),
  ("tf", "'Otherwise' doesn't need a real action stated before it — it can stand alone as the condition.", False),
  ("mcq", "'Without your help, I couldn't have finished' means…", ["If you hadn't helped me, I couldn't have finished.", "You didn't help me.", "I finished without any help.", "If you help me, I'll finish."], 0),
  ("mcq", "He approved the budget ___ checking the figures.", ["without", "but for", "otherwise", "unless"], 0),
  ("mcq", "Take an umbrella; ___ you'll get soaked.", ["otherwise", "but for", "without", "provided"], 0),
])

quiz("b2-10", course=B2, n=10, lesson="lesson-10-advanced-wish.html",
  name="Advanced Wish / If Only",
  structures="wish/if only + past perfect (own regret), wish + would (someone else's behaviour), layered regret with a third conditional",
  tags=["wish", "if-only", "regret"], qs=[
  ("mcq", "I wish the manager ___ the deadline before we all stayed up all night.", ["had mentioned", "would mention", "mentions", "has mentioned"], 0),
  ("mcq", "I wish he ___ interrupting every single meeting!", ["would stop", "stops", "will stop", "has stopped"], 0),
  ("gap", "If only she ___ (tell) me earlier, I could have rearranged my schedule.", "had told", ["'d told", "’d told"]),
  ("tf", "'Wish + would' is almost never used about yourself.", True),
  ("spot", "I wish I would stop being late all the time.", ["I wish", "I would stop", "being late", "all the time"], 1),
  ("gap", "I wish I'd backed up the file, because if I ___, I wouldn't have lost everything.", "had", []),
  ("wb", "Unscramble the missing word: I wish I had ___ the contract more carefully.", "READ"),
  ("mcq", "'I wish he would have told me sooner' mainly expresses…", ["annoyance about someone's past (in)action", "a neutral fact", "a future plan", "a polite request"], 0),
  ("tf", "In layered regret, the 'if' clause should restate the same past action as the wish.", True),
  ("mcq", "If only I ___ the schedule, I wouldn't have missed the flight.", ["had checked", "checked", "would check", "have checked"], 0),
  ("gap", "I wish I ___ (not/sign) that agreement.", "hadn't signed", ["had not signed", "hadn’t signed"]),
  ("mcq", "I wish I ___ so much at the party last night — I feel awful today.", ["hadn't eaten", "didn't eat", "wouldn't eat", "haven't eaten"], 0),
])

quiz("b2-11", course=B2, n=11, lesson="lesson-11-passive-combined-aspects.html",
  name="Passive With Combined Aspects",
  structures="passive continuous (is/was being + past participle) and perfect participle passive (having been + past participle)",
  tags=["passive-voice", "passive-continuous", "participle-clauses"], qs=[
  ("mcq", "The proposal ___ discussed in the boardroom as we speak.", ["is being", "has been", "was", "is"], 0),
  ("mcq", "___ signed by both parties, the agreement finally took effect.", ["Having been", "Being", "Having", "To be"], 0),
  ("gap", "The new servers ___ being installed while the office is closed.", "are", []),
  ("tf", "'Having been + past participle' describes a completed passive step before the main event.", True),
  ("spot", "Having been reviewed, we approved the report.", ["Having been reviewed", "we approved", "the report"], 1),
  ("mcq", "The contract ___ by legal right now.", ["is being reviewed", "is reviewing", "has reviewed", "being reviewed"], 0),
  ("wb", "Unscramble the missing word: ___ been delayed twice, the launch was finally rescheduled.", "HAVING"),
  ("gap", "When I arrived, the room ___ (clean), so I waited outside.", "was being cleaned", []),
  ("mcq", "Which pattern combines passive with continuous aspect?", ["being + past participle", "to be + past participle", "having + past participle", "been + -ing"], 0),
  ("tf", "In 'Having been approved, the budget was released', the budget is the subject of both parts.", True),
  ("mcq", "I hate ___ interrupted when I'm speaking.", ["being", "having been", "be", "to being"], 0),
  ("mcq", "The patient ___ by a specialist when the power went out.", ["was being examined", "was examining", "has been examining", "is examined"], 0),
])

quiz("b2-12", course=B2, n=12, lesson="lesson-12-impersonal-get-passive.html",
  name="Impersonal Passive & Get-Passive",
  structures="It is said/believed that…; subject + is thought to (have) + verb; get + past participle (informal passive)",
  tags=["passive-voice", "impersonal-passive", "get-passive"], qs=[
  ("mcq", "___ that the company is planning layoffs.", ["It is rumoured", "It rumours", "It is rumouring", "It has rumoured"], 0),
  ("mcq", "The manager ___ have approved the request without checking the budget.", ["is thought to", "is thinking to", "thinks to", "is thought that"], 0),
  ("gap", "He ___ fired after the scandal broke. (informal)", "got", []),
  ("tf", "The get-passive is a good choice for formal reports and academic writing.", False),
  ("spot", "It is got said that the CEO will resign.", ["It", "is got said", "that the CEO", "will resign"], 1),
  ("mcq", "'She got promoted last month' sounds…", ["informal and conversational", "formal and official", "legally binding", "old-fashioned"], 0),
  ("wb", "Unscramble the missing word: It is ___ that the talks collapsed over pricing.", "UNDERSTOOD"),
  ("gap", "He is believed ___ left the country last week.", "to have", []),
  ("mcq", "Which is the formal equivalent of 'She got promoted'?", ["She was promoted.", "She got herself promote.", "It got promoted her.", "She is getting promote."], 0),
  ("tf", "'It is believed that…' lets us report a belief without saying who holds it.", True),
  ("mcq", "The suspect is said ___ in the area at the time.", ["to have been", "to be been", "that he was", "having been"], 0),
  ("mcq", "Our car ___ last night — we had to call the police.", ["got stolen", "got steal", "was stealing", "has stolen"], 0),
])

quiz("b2-13", course=B2, n=13, lesson="lesson-13-nominalisation.html",
  name="Nominalisation",
  structures="verb → noun (-ion, -ment, -al, -ure) and adjective → noun (-ity, -ness, -ance/-ence) for formal, impersonal style",
  tags=["nominalisation", "formal-english", "word-formation"], qs=[
  ("mcq", "The noun form of 'analyse' is…", ["analysis", "analysement", "analysation", "analysingness"], 0),
  ("gap", "The noun form of 'significant' is ___.", "significance", []),
  ("mcq", "'They failed to meet the deadline' → 'There was a ___ to meet the deadline.'", ["failure", "failing", "fail", "failness"], 0),
  ("tf", "Nominalisation tends to make writing more formal and impersonal.", True),
  ("wb", "Unscramble the noun form of 'decide'.", "DECISION"),
  ("gap", "'We will assess the risks' → 'An ___ of the risks will be conducted.'", "assessment", []),
  ("mcq", "'They decided to expand the team', nominalised, becomes…", ["A decision was made to expand the team.", "They will decide to expand the team.", "Deciding, they expanded the team.", "The team decided to expand."], 0),
  ("spot", "The implement of the new policy was swift.", ["The implement", "of the new policy", "was swift"], 0),
  ("mcq", "Which verb collocates with 'a decision' in formal writing?", ["reach", "do", "get", "put"], 0),
  ("tf", "Heavy nominalisation is the best style for a friendly, casual email.", False),
  ("gap", "The noun form of 'aware' is ___.", "awareness", []),
  ("mcq", "The noun form of 'efficient' is…", ["efficiency", "efficientness", "efficience", "efficiention"], 0),
])

quiz("b2-14", course=B2, n=14, lesson="lesson-14-advanced-articles-quantifiers.html",
  name="Advanced Articles & Quantifiers",
  structures="generic articles (the/a + singular, zero + plural); few vs a few, little vs a little; a number of, a great deal of, the majority of",
  tags=["articles", "quantifiers"], qs=[
  ("mcq", "___ smartphone has changed how we communicate at work. (the invention in general)", ["The", "A the", "An", "Some"], 0),
  ("mcq", "___ of employees surveyed said they preferred remote work.", ["The majority", "The majorities", "A majorities", "Majority"], 0),
  ("gap", "There was ___ interest in the proposal, so it was quietly dropped.", "little", []),
  ("tf", "'Few employees complained' suggests that almost none did.", True),
  ("spot", "A number of candidate had the exact skills we needed.", ["A number of", "candidate", "had the exact skills", "we needed"], 1),
  ("mcq", "'A few managers understood the new system' suggests…", ["some did — a reasonable number", "almost none did", "all of them did", "none of them did"], 0),
  ("wb", "Unscramble the missing word: The project required a great ___ of effort.", "DEAL"),
  ("gap", "___ tiger is an endangered species. (the species in general)", "The", []),
  ("mcq", "Which quantifier goes with an UNCOUNTABLE noun?", ["a great deal of", "a number of", "many", "a few"], 0),
  ("tf", "'A number of' is followed by a singular noun, e.g. 'a number of candidate'.", False),
  ("mcq", "___ time was left, so we had to rush.", ["Little", "A few", "Few", "Many"], 0),
  ("mcq", "___ of the staff agreed with the proposal, so it was approved.", ["The majority", "A great deal", "Little", "A little"], 0),
])
