from common import quiz, B2

quiz("b2-15", course=B2, n=15, lesson="lesson-15-participle-clauses.html",
  name="Participle Clauses",
  structures="present participle (-ing), past participle (-ed/3rd form) and having + past participle clauses; dangling participles",
  tags=["participle-clauses"], qs=[
  ("mcq", "___ the budget twice, the finance team still found an error.", ["Having checked", "Having check", "Checked", "Being check"], 0),
  ("mcq", "___ by the sudden resignation, the board called an emergency meeting.", ["Alarmed", "Alarming", "Having alarmed", "To alarm"], 0),
  ("gap", "The candidate ___ (give) the strongest interview got the offer.", "giving", []),
  ("tf", "In a participle clause, the implied subject must be the same as the subject of the main clause.", True),
  ("spot", "Walking into the office, the lights were off.", ["Walking into the office", "the lights", "were off"], 1),
  ("mcq", "'Written in haste, the memo contained several errors.' The participle clause has a…", ["passive meaning", "active meaning", "future meaning", "question form"], 0),
  ("wb", "Unscramble the missing word: ___ exhausted, she left the meeting early.", "FEELING"),
  ("gap", "___ (install) overnight, the server updates caused no disruption at all.", "Installed", []),
  ("mcq", "'Having signed the contract, they shook hands' means…", ["They signed first, then shook hands.", "They shook hands, then signed.", "They did both at the same moment.", "They didn't sign."], 0),
  ("tf", "'The report, written by three departments, took months' = 'The report, which was written by three departments, took months.'", True),
  ("spot", "Having finish the project, the team celebrated.", ["Having finish", "the project", "the team", "celebrated"], 0),
  ("mcq", "Which sentence contains a dangling participle (an error)?", ["Driving to work, the rain started.", "Driving to work, I noticed the rain.", "Having finished the report, she sent it.", "Delayed by traffic, he arrived late."], 0),
])

quiz("b2-16", course=B2, n=16, lesson="lesson-16-advanced-relative-clauses.html",
  name="Advanced Relative Clauses",
  structures="whereby, whereupon, whole-clause 'which', preposition + whom/which (formal)",
  tags=["relative-clauses", "formal-english"], qs=[
  ("mcq", "The company introduced a scheme ___ staff could work four days a week.", ["whereby", "whereupon", "which", "what"], 0),
  ("mcq", "He missed the deadline, ___ annoyed the entire team.", ["which", "that", "what", "who"], 0),
  ("gap", "The client to ___ we submitted the proposal has not replied yet.", "whom", []),
  ("tf", "'Whereby' means 'by which' or 'through which'.", True),
  ("spot", "The colleague to who I reported was very supportive.", ["The colleague", "to who", "I reported", "was very supportive"], 1),
  ("mcq", "She announced her resignation, ___ the room fell silent.", ["whereupon", "whereby", "which", "that"], 0),
  ("wb", "Unscramble the missing word: We have a policy ___ latecomers are fined.", "WHEREBY"),
  ("mcq", "In 'She was promoted, which surprised nobody', 'which' refers to…", ["the whole idea that she was promoted", "the word 'promoted' only", "'nobody'", "'she'"], 0),
  ("tf", "In formal style, a preposition can be followed by 'that': 'the team with that I worked'.", False),
  ("gap", "This is the report on ___ the decision was based.", "which", []),
  ("mcq", "Which version is the most formal?", ["the colleague to whom I reported", "the colleague who I reported to", "the colleague I reported to", "the colleague that I reported to"], 0),
  ("mcq", "The period during ___ the company expanded was short.", ["which", "whom", "that", "who"], 0),
])

quiz("b2-17", course=B2, n=17, lesson="lesson-17-ellipsis-substitution.html",
  name="Ellipsis & Substitution",
  structures="ellipsis (if necessary, if unsure); substitution with so/not, one/ones; so/neither + auxiliary + subject",
  tags=["ellipsis", "substitution"], qs=[
  ("mcq", "He didn't finish the report, and ___ did his colleague.", ["neither", "so", "either", "too"], 0),
  ("gap", "'Will the client approve it?' — 'I hope ___.'", "so", []),
  ("mcq", "'She finished early, and so did I' means…", ["I also finished early.", "I finished later.", "I didn't finish.", "She finished because of me."], 0),
  ("tf", "After verbs like think, hope and expect, 'so' can replace a whole clause: 'I expect so.'", True),
  ("spot", "She didn't attend the meeting, and I neither.", ["She didn't attend", "the meeting", "and I neither"], 2),
  ("mcq", "'Contact HR if unsure' is short for…", ["Contact HR if you are unsure.", "Contact HR because you are unsure.", "Contact HR unless you are unsure.", "HR is unsure."], 0),
  ("wb", "Unscramble the missing word: I'd like the blue folder, not the red ___.", "ONE"),
  ("gap", "'Is it going to rain tomorrow?' — 'I hope ___.' (= I hope it isn't)", "not", []),
  ("tf", "'One/ones' can replace uncountable nouns such as 'information' or 'advice'.", False),
  ("mcq", "Please revise the draft ___ needed.", ["if", "unless", "so", "one"], 0),
  ("mcq", "'I can't swim.' — '___ can I.'", ["Neither", "So", "Either", "Too"], 0),
  ("mcq", "'Do you think it'll rain?' — 'I don't think ___.'", ["so", "it", "one", "not"], 0),
])

quiz("b2-18", course=B2, n=18, lesson="lesson-18-negative-inversion.html",
  name="Negative Inversion for Emphasis",
  structures="Never/Rarely/Seldom + auxiliary + subject; Not only… but also; Under no circumstances / On no account / Little",
  tags=["inversion", "emphasis", "negative-adverbials"], qs=[
  ("mcq", "Never ___ such a disorganised handover before.", ["have I seen", "I have seen", "I saw", "saw I"], 0),
  ("mcq", "Rarely ___ this divided on a single issue.", ["has the board been", "the board has been", "has been the board", "the board was"], 0),
  ("gap", "Not only ___ she meet the deadline, but she also exceeded every target.", "did", []),
  ("tf", "If there's no auxiliary, you add do/does/did: 'Rarely does he arrive on time.'", True),
  ("spot", "Rarely he arrives on time for meetings.", ["Rarely", "he arrives", "on time", "for meetings"], 1),
  ("mcq", "Under no circumstances ___ this data with a third party.", ["should you share", "you should share", "share you", "you share"], 0),
  ("wb", "Unscramble the missing word: ___ did we know that the market was about to crash.", "LITTLE"),
  ("gap", "Seldom ___ she complain, even under pressure.", "does", []),
  ("tf", "'I have never seen such chaos' needs inversion because it contains 'never'.", False),
  ("mcq", "On no account ___ the door unlocked.", ["must you leave", "you must leave", "you leave", "leave you"], 0),
  ("spot", "Never before the company has faced such pressure.", ["Never before", "the company has faced", "such pressure"], 1),
  ("mcq", "Only after the meeting ___ how serious the problem was.", ["did I realise", "I realised", "I did realise", "realised I"], 0),
])

quiz("b2-19", course=B2, n=19, lesson="lesson-19-fronting-information-structure.html",
  name="Fronting & Information Structure",
  structures="fronted object, fronted complement (A key issue is…), Such/So + be + subject + that…",
  tags=["fronting", "emphasis", "information-structure"], qs=[
  ("mcq", "___ was the level of interest that the event had to be moved to a bigger venue.", ["Such", "So", "There", "It"], 0),
  ("mcq", "___ still unresolved is the question of funding.", ["Also", "There", "It", "So"], 0),
  ("gap", "So strong ___ the evidence that the case was closed quickly.", "was", []),
  ("tf", "Fronting is optional — writers choose it for emphasis or to link ideas smoothly.", True),
  ("spot", "Such the demand was that tickets sold out in minutes.", ["Such", "the demand was", "that tickets", "sold out in minutes"], 1),
  ("mcq", "'A particularly thorny issue is client confidentiality.' What has been fronted?", ["the complement", "the object", "an adverb of time", "a negative adverbial"], 0),
  ("wb", "Unscramble the missing word: ___ was the demand that we sold out in an hour.", "SUCH"),
  ("gap", "A key challenge ___ maintaining morale during the restructuring.", "is", []),
  ("mcq", "Which sentence fronts the OBJECT?", ["This report, we cannot publish yet.", "We cannot publish this report yet.", "Such was the demand that we sold out.", "A major concern is data security."], 0),
  ("tf", "Fronting an object normally requires subject–verb inversion.", False),
  ("mcq", "So ___ that nobody could hear the speaker.", ["loud was the music", "the music was loud", "was loud the music", "loud the music was"], 0),
  ("mcq", "Such ___ his anger that he couldn't speak.", ["was", "were", "did", "had"], 0),
])

quiz("b2-20", course=B2, n=20, lesson="lesson-20-discourse-capstone.html",
  name="Formal Connectors: Nonetheless, Notwithstanding, Whereas",
  structures="nonetheless, notwithstanding + noun phrase, whereas, in light of, insofar as",
  tags=["connectors", "formal-english", "discourse"], qs=[
  ("mcq", "The results were disappointing; ___, the team pressed on.", ["nonetheless", "therefore", "whereas", "insofar as"], 0),
  ("mcq", "___ the risks involved, the board approved the investment.", ["Notwithstanding", "Because of", "Whereas", "Insofar as"], 0),
  ("gap", "Marketing prioritised speed, ___ engineering prioritised stability.", "whereas", ["while"]),
  ("tf", "'Notwithstanding' is followed by a noun phrase, not a full clause.", True),
  ("spot", "Notwithstanding the project was delayed, it finished on budget.", ["Notwithstanding", "the project was delayed", "it finished", "on budget"], 1),
  ("mcq", "___ the new evidence, the policy will need to be reviewed.", ["In light of", "In case of", "Whereas", "Nonetheless"], 0),
  ("wb", "Unscramble the missing word: Sales fell; ___, profit rose.", "NONETHELESS"),
  ("gap", "The plan is useful ___ as it identifies the main risks. (= to the extent that)", "insofar", ["in so far"]),
  ("mcq", "'Nonetheless' is closest in meaning to…", ["however", "therefore", "because", "for example"], 0),
  ("tf", "'In light of' means 'in spite of'.", False),
  ("mcq", "Which sentence uses 'whereas' correctly?", ["Whereas the first team focused on design, the second focused on testing.", "Whereas the delays, the project finished on time.", "The results were poor; whereas, we continued.", "Whereas of the rain, we stayed inside."], 0),
  ("mcq", "The policy is fair ___ it treats everyone equally.", ["insofar as", "notwithstanding", "in light of", "nonetheless"], 0),
])
