from common import quiz

quiz("site-conditionals", lesson="/lessons/english-conditionals.html",
  title="Conditionals — Lesson Quiz", category="Grammar",
  desc="Zero, first, second, third and mixed conditionals, unless, inversion (should/were/had) and I wish",
  tags=["conditionals", "lesson-quiz"], qs=[
  ("mcq", "If you heat ice, it ___.", ["melts", "will have melted", "would melt", "melted"], 0),
  ("gap", "If it ___ (rain) tomorrow, we will cancel the trip.", "rains", []),
  ("tf", "In formal English, 'were' is used for all subjects in the second conditional: 'If I were you…'.", True),
  ("mcq", "If she ___ harder, she would have passed.", ["had studied", "studied", "would study", "has studied"], 0),
  ("spot", "If it will rain tomorrow, we'll stay at home.", ["If", "it will rain", "tomorrow", "we'll stay at home"], 1),
  ("mcq", "If I had taken that job, I ___ rich now.", ["would be", "would have been", "will be", "had been"], 0),
  ("gap", "___ she studied, she would have passed. (formal: 'If she had studied…')", "Had", []),
  ("wb", "Unscramble the word that means 'if not': We'll miss the train ___ we leave now.", "UNLESS"),
  ("mcq", "Which is the formal, inverted version of 'If it rains tomorrow, …'?", ["Should it rain tomorrow, …", "Were it rains tomorrow, …", "Had it rain tomorrow, …", "Does it rain tomorrow, …"], 0),
  ("tf", "A mixed conditional can combine a past cause with a present result.", True),
  ("gap", "What would you do if you ___ (win) the lottery?", "won", []),
  ("mcq", "I wish I ___ more time — I'm so busy these days.", ["had", "have", "will have", "am having"], 0),
])

quiz("site-verb-tenses", lesson="/lessons/english-verb-tenses.html",
  title="Verb Tenses — Lesson Quiz", category="Grammar",
  desc="The 12 tenses, stative verbs, used to, time clauses and the passive across tenses",
  tags=["verb-tenses", "lesson-quiz"], qs=[
  ("mcq", "I ___ when the phone rang.", ["was reading", "read", "have read", "am reading"], 0),
  ("gap", "By the time I arrived, she ___ (leave).", "had left", ["'d left", "’d left"]),
  ("tf", "Stative verbs such as 'know', 'want' and 'own' are not normally used in continuous forms.", True),
  ("mcq", "She ___ Paris last summer.", ["visited", "has visited", "was visiting", "has been visiting"], 0),
  ("spot", "I am knowing the answer to that question.", ["I", "am knowing", "the answer", "to that question"], 1),
  ("mcq", "By this time next year, I ___ my degree.", ["will have finished", "will finish", "am finishing", "finish"], 0),
  ("gap", "He was exhausted because he ___ (work) all night.", "had been working", ["had worked"]),
  ("mcq", "When I was a child, I ___ play outside every day.", ["used to", "am used to", "was used to", "use to"], 0),
  ("wb", "Unscramble the missing word: I've lived here ___ 2019.", "SINCE"),
  ("tf", "'As soon as I will arrive, I'll call you' is correct.", False),
  ("gap", "The report ___ (write) by the team at the moment.", "is being written", []),
  ("mcq", "Which sentence is correct?", ["She has been waiting for two hours.", "She is waiting for two hours.", "She waits since two hours.", "She has waited since two hours."], 0),
])

quiz("site-pronunciation", lesson="/lessons/english-pronunciation.html",
  title="Pronunciation — Lesson Quiz", category="Use of English",
  desc="IPA, the schwa, voiced and voiceless sounds, minimal pairs, word stress and connected speech (British English)",
  tags=["pronunciation", "ipa", "lesson-quiz"], qs=[
  ("mcq", "How many phonemes (sounds) does British English have?", ["44", "26", "36", "52"], 0),
  ("tf", "The schwa /ə/ is never stressed.", True),
  ("mcq", "Which word begins with the voiced 'th' sound /ð/?", ["this", "think", "thank", "three"], 0),
  ("mcq", "In 'banana' /bəˈnɑːnə/, which syllable is stressed?", ["the second", "the first", "the third", "all of them equally"], 0),
  ("mcq", "When 'record' is a NOUN, where is the stress?", ["on the first syllable: REcord", "on the second syllable: reCORD"], 0),
  ("tf", "In British English, the 'r' in 'car park' is pronounced.", False),
  ("mcq", "Which of these is a minimal pair?", ["ship / sheep", "cat / dog", "light / lights", "phone / photo"], 0),
  ("wb", "Unscramble the name of the most common vowel sound in English.", "SCHWA"),
  ("mcq", "Which IPA symbol shows the 'sh' sound in 'shoe'?", ["/ʃ/", "/ʒ/", "/tʃ/", "/s/"], 0),
  ("mcq", "What is the difference between /p/ and /b/?", ["/b/ is voiced; /p/ is voiceless", "/p/ is voiced; /b/ is voiceless", "/b/ uses the tongue; /p/ uses the lips", "There is no difference"], 0),
  ("gap", "British English has 20 vowel sounds and ___ consonant sounds.", "24", ["twenty-four", "twenty four"]),
  ("mcq", "In fast speech, 'next day' often sounds like 'nex day'. A sound disappears. This is called…", ["elision", "linking", "intonation", "word stress"], 0),
])

quiz("site-transitional-words", lesson="/lessons/english-transitional-words.html",
  title="Transitional Words — Lesson Quiz", category="Use of English",
  desc="Connectives for addition, contrast, concession, cause, result, example and clarification",
  tags=["transitional-words", "linking-words", "lesson-quiz"], qs=[
  ("mcq", "He worked hard. ___, he failed to meet the deadline.", ["However", "Therefore", "Moreover", "For instance"], 0),
  ("gap", "The match was postponed ___ to heavy rainfall.", "due", ["owing"]),
  ("tf", "'However' can join two clauses with just a comma: 'He was tired, however he carried on.'", False),
  ("mcq", "The report was late. ___, it contained several factual errors.", ["Furthermore", "Nevertheless", "Consequently", "In contrast"], 0),
  ("mcq", "Which sentence is correct?", ["Despite working through the night, she didn't finish in time.", "Despite she worked through the night, she didn't finish in time.", "Despite of working through the night, she didn't finish in time.", "Despite that she worked through the night, she didn't finish in time."], 0),
  ("wb", "Unscramble the missing word: We lost the client. As a ___, the project was cancelled.", "RESULT"),
  ("mcq", "'In other words' is used to…", ["rephrase or clarify an idea", "add a contrasting idea", "give a reason", "end a list"], 0),
  ("gap", "She was exhausted. Even ___, she kept going.", "so", []),
  ("tf", "'Because of', 'due to' and 'owing to' are followed by a noun phrase, not a full clause.", True),
  ("mcq", "On the one hand, we need progress. ___, we must protect what we have.", ["On the other hand", "In addition", "For example", "As a result"], 0),
  ("spot", "Not only she missed the meeting, but she also failed to apologise.", ["Not only", "she missed", "but she also", "failed to apologise"], 1),
  ("gap", "___ instance, consider what happens when two cultures meet for the first time.", "For", []),
])

quiz("site-hedging-language", lesson="/lessons/english-hedging-language.html",
  title="Hedging Language — Lesson Quiz", category="Use of English",
  desc="Softening claims with modals, tend to, appear/seem, adverbs, approximators and attribution",
  tags=["hedging", "academic-english", "lesson-quiz"], qs=[
  ("mcq", "Which is the most tentative (hedged) claim?", ["This may explain the results.", "This explains the results.", "This definitely explains the results.", "This clearly explains the results."], 0),
  ("gap", "The results should be interpreted with ___.", "caution", []),
  ("tf", "In 'The pattern should become clearer with more data', 'should' means 'it is likely', not 'it is an obligation'.", True),
  ("mcq", "Prices ___ to rise during periods of instability — it's a general pattern.", ["tend", "may", "should", "could"], 0),
  ("wb", "Unscramble the missing word: ___ speaking, the intervention was effective.", "BROADLY"),
  ("mcq", "It would ___ that the hypothesis is supported.", ["appear", "tend", "likely", "possible"], 0),
  ("spot", "The data appear to supporting this interpretation.", ["The data", "appear to", "supporting", "this interpretation"], 2),
  ("mcq", "Which of these is an APPROXIMATOR?", ["approximately", "may", "according to", "it is claimed"], 0),
  ("tf", "'Probably' expresses less certainty than 'possibly'.", False),
  ("gap", "___ some extent, the findings confirm the theory.", "To", []),
  ("mcq", "'According to recent reports, …' is an example of which kind of hedging?", ["attribution", "approximation", "limitation", "a modal verb"], 0),
  ("gap", "The variation is ___ explained by social factors — but not entirely.", "largely", ["mainly", "mostly"]),
])

quiz("site-workplace-eq", lesson="/lessons/workplace-eq.html",
  title="Workplace EQ — Lesson Quiz", category="Use of English",
  desc="British workplace phrases — introductions, polite requests, understatement, emails and disagreeing diplomatically",
  tags=["workplace", "business-english", "lesson-quiz"], qs=[
  ("mcq", "Which request works best with a senior colleague?", ["I was wondering if you could take a look at this.", "Look at this.", "Please look at this now.", "You need to look at this."], 0),
  ("tf", "In English, a title like 'Mrs' or 'Dr' goes with a surname, not a first name.", True),
  ("mcq", "A British colleague says 'That's an interesting idea' and asks nothing more. They probably mean…", ["I don't think that will work.", "I love it — let's start now.", "Please tell me more.", "I didn't hear you."], 0),
  ("gap", "Would you ___ sending me the latest version?", "mind", []),
  ("mcq", "Which is a safe small-talk opener at a work event?", ["Did you have far to come?", "How much do you earn?", "How old are you?", "Who did you vote for?"], 0),
  ("tf", "'With the greatest respect…' is usually a sincere compliment.", False),
  ("wb", "Unscramble the missing word: Just ___ up on my email below.", "FOLLOWING"),
  ("mcq", "In British English, 'It's not bad at all' usually means…", ["It's good.", "It's terrible.", "It's average.", "I haven't seen it."], 0),
  ("gap", "Kind ___ — the safest sign-off for a first professional email.", "regards", []),
  ("spot", "Nice to meet you, Mrs Helen.", ["Nice", "to meet you", "Mrs Helen"], 2),
  ("mcq", "'I'm not entirely convinced' is understood as…", ["a polite but firm objection", "enthusiastic agreement", "a request for more time", "a joke"], 0),
  ("gap", "Could you ___ check the dates for me? (a small word that makes the task sound quick)", "just", []),
])
