from common import quiz

quiz("site-collocations", lesson="/lessons/english-collocations.html",
  title="Collocations — Lesson Quiz", category="Vocabulary",
  desc="Words that go together — make/do, strong vs weak collocations and formal vs informal register",
  tags=["collocations", "lesson-quiz"], qs=[
  ("mcq", "We had ___ rain all weekend.", ["heavy", "strong", "big", "hard"], 0),
  ("gap", "Everyone ___ mistakes — what matters is how you respond to them.", "makes", []),
  ("tf", "'Do a decision' is an acceptable alternative to 'make a decision'.", False),
  ("mcq", "Which is the most formal way to say 'get off a bus'?", ["alight from a bus", "hop off a bus", "get off a bus", "jump off a bus"], 0),
  ("spot", "She has done remarkable progress in her second year of study.", ["She has", "done", "remarkable progress", "her second year"], 1),
  ("mcq", "The chair decided to ___ the meeting until next week.", ["adjourn", "terminate", "conduct", "alight"], 0),
  ("wb", "Unscramble the missing word: Please make an ___ to arrive on time.", "EFFORT"),
  ("mcq", "The police will ___ an investigation into the incident.", ["conduct", "make", "do", "take"], 0),
  ("tf", "Strong collocations have only a small, predictable set of partner words — e.g. 'heavy rain', not 'strong rain'.", True),
  ("mcq", "Which is the INFORMAL way to say 'propose marriage'?", ["pop the question", "request a union", "ask for a hand", "drop the question"], 0),
  ("mcq", "Which of these is a FIXED collocation — no word can be changed?", ["to and fro", "very big", "a nice day", "quite difficult"], 0),
  ("gap", "I'm starving — let's grab a ___ to eat.", "bite", []),
])

quiz("site-determiners", lesson="/lessons/english-determiners.html",
  title="Determiners — Lesson Quiz", category="Grammar",
  desc="Articles (a/an, the, zero article), quantifiers, predeterminers and possessives",
  tags=["determiners", "articles", "lesson-quiz"], qs=[
  ("mcq", "She wants to be ___ engineer.", ["an", "a", "the", "(no article)"], 0),
  ("gap", "I need ___ hour to finish this work.", "an", []),
  ("tf", "Rivers take the definite article: the Thames, the Nile, the Amazon.", True),
  ("mcq", "___ love is the most powerful force in the world.", ["(no article)", "The", "A", "An"], 0),
  ("spot", "He is an university professor.", ["He is", "an", "university", "professor"], 1),
  ("mcq", "Which noun phrase is grammatical?", ["all my friends", "my all friends", "the my friends", "my the friends"], 0),
  ("gap", "What ___ wonderful surprise!", "a", []),
  ("mcq", "Only ___ people came to the meeting, so it finished early.", ["a few", "a little", "much", "less"], 0),
  ("tf", "A noun phrase can have two central determiners, e.g. 'the my book'.", False),
  ("wb", "Unscramble the predeterminer that means 'the two of them': ___ the doctors agreed.", "BOTH"),
  ("mcq", "She is ___ only person who understands this.", ["the", "an", "a", "(no article)"], 0),
  ("gap", "___ Sahara is the largest hot desert in the world.", "The", []),
])

quiz("site-sentences-clauses", lesson="/lessons/english-sentences-and-clauses.html",
  title="Sentences & Clauses — Lesson Quiz", category="Grammar",
  desc="Simple, compound, complex and compound-complex sentences; main, subordinate and relative clauses",
  tags=["sentences", "clauses", "lesson-quiz"], qs=[
  ("mcq", "'She studied hard, but she still found the exam difficult.' What type of sentence is this?", ["compound", "simple", "complex", "compound-complex"], 0),
  ("tf", "A simple sentence can have a compound subject, e.g. 'The teacher and her students worked through the night.'", True),
  ("mcq", "Which sentence is a comma splice (an error)?", ["She was tired, she went to bed early.", "She was tired, so she went to bed early.", "She was tired; she went to bed early.", "Because she was tired, she went to bed early."], 0),
  ("gap", "___ she was exhausted, she kept working until midnight.", "Although", ["Though", "Even though"]),
  ("mcq", "In 'When she finally spoke, her voice was barely a whisper', the part 'When she finally spoke' is…", ["a subordinate (dependent) clause", "a main clause", "a relative clause", "a noun phrase"], 0),
  ("mcq", "She smiled, ___ surprised everyone in the room.", ["which", "that", "who", "what"], 0),
  ("tf", "'However' is a coordinating conjunction, so 'It rained, however we went out' is correct.", False),
  ("wb", "Unscramble the missing conjunction: She did not speak, ___ did she move.", "NOR"),
  ("mcq", "Which sentence is COMPLEX?", ["I stayed at home because it was raining.", "I stayed at home all day.", "It was raining, so I stayed at home.", "It was raining; I stayed at home."], 0),
  ("spot", "Although she was late but she didn't apologise.", ["Although", "she was late", "but", "she didn't apologise"], 2),
  ("gap", "A person ___ never tells lies is hard to find.", "who", ["that"]),
  ("tf", "When a subordinate clause comes first, it is normally followed by a comma: 'Although she was tired, she continued.'", True),
])

quiz("site-inversion", lesson="/lessons/english-inversion-negative-adverbials.html",
  title="Inversion & Negative Adverbials — Lesson Quiz", category="Grammar",
  desc="Formal inversion after never, rarely, seldom, not only, no sooner, hardly, only then, under no circumstances",
  tags=["inversion", "negative-adverbials", "lesson-quiz"], qs=[
  ("mcq", "Rarely ___ in public.", ["does she speak", "she speaks", "she does speak", "speaks she"], 0),
  ("gap", "No sooner had she arrived ___ the phone rang.", "than", []),
  ("tf", "'Hardly' and 'scarcely' pair with 'when' or 'before' — never with 'than'.", True),
  ("mcq", "Never before ___ such a sight.", ["had I seen", "I had seen", "saw I", "I saw"], 0),
  ("spot", "Not only did she win the race, but also did she break the record.", ["Not only", "did she win", "but also did she break", "the record"], 2),
  ("wb", "Unscramble the missing word: Little ___ the world know that the invention would change everything.", "DID"),
  ("mcq", "Under no circumstances ___ leave the building.", ["should you", "you should", "you do", "do you should"], 0),
  ("gap", "Only then ___ they understand what had happened.", "did", []),
  ("tf", "In formal English, inversion after a fronted negative adverbial is optional.", False),
  ("mcq", "Choose the correct sentence.", ["Seldom has a single idea changed history so completely.", "Seldom a single idea has changed history so completely.", "Seldom has changed a single idea history so completely.", "Seldom did a single idea has changed history so completely."], 0),
  ("gap", "At no time during the crisis ___ the commander lose his composure.", "did", []),
  ("wb", "Unscramble the adverbial: ___ had we arrived when the storm began.", "HARDLY"),
])

quiz("site-cleft-sentences", lesson="/lessons/english-cleft-sentences.html",
  title="Cleft Sentences — Lesson Quiz", category="Grammar",
  desc="It-clefts, wh-clefts, reversed wh-clefts, all-clefts, there-clefts and negative clefts",
  tags=["cleft-sentences", "emphasis", "lesson-quiz"], qs=[
  ("mcq", "Plain sentence: 'Sarah solved the problem.' Which cleft puts the focus on Sarah?", ["It was Sarah who solved the problem.", "What Sarah solved was the problem.", "All Sarah did was solve it.", "It was the problem that Sarah solved."], 0),
  ("gap", "___ she needs is a rest.", "What", []),
  ("tf", "In 'It was at midnight that they finally reached an agreement', the focus is on the time.", True),
  ("mcq", "Which cleft stresses that smiling was the ONLY thing he did?", ["All he did was smile.", "It was him who smiled.", "It was then that he smiled.", "Smiling is what people do."], 0),
  ("spot", "What the company requires are better communication.", ["What", "the company requires", "are", "better communication"], 2),
  ("wb", "Unscramble the missing word: It was her calm manner ___ persuaded the committee.", "THAT"),
  ("mcq", "'A rest is what she needs.' What type of cleft is this?", ["reversed wh-cleft", "it-cleft", "all-cleft", "negative cleft"], 0),
  ("gap", "It was not luck ___ hard work that brought success.", "but", []),
  ("tf", "In an all-cleft, the verb after 'be' is usually a bare infinitive: 'All she did was listen.'", True),
  ("mcq", "'They met in Rome.' Which sentence puts the focus on the place?", ["It was in Rome that they met.", "It was they who met in Rome.", "What they did was meet.", "All they did was meet in Rome."], 0),
  ("gap", "It was Maria ___ found the key.", "who", ["that"]),
  ("mcq", "Which sentence is NOT a cleft sentence?", ["Maria found the key yesterday.", "It was Maria who found the key.", "What Maria found was the key.", "The key is what Maria found."], 0),
])
